class ClinicModel:
    clinic_no: str
    trial: str
    city: str
    name: str
    ntc: bool
    rat: bool
    working_weekday: str
    working_saturday: str
    working_sunday: str
    working_holiday: str
    call: str
    location: str
    competent_name: str
    competent_call: str
    description: str
    congestion: str